spring:
  cassandra:
    contact-points: 
      - 127.0.0.1:9042
    keyspace-name: atkins
    local-datacenter: datacenter1
    request:
      timeout: 10s
      consistency: ONE
    connection:
      init-query-timeout: 10s

logging:
  level:
    "[com.datastax.oss.driver]": DEBUG
    "[org.springframework.data.cassandra]": DEBUG
    # Additional logging for troubleshooting
    "[com.scylladb]": DEBUG
