server:
  port: 8080

spring:
  application:
    name: atkins
  cassandra:
    contact-points: 
      - 127.0.0.1:9042
      - 127.0.0.1:9043
      - 127.0.0.1:9044
    keyspace-name: atkins
    local-datacenter: datacenter1
    request:
      timeout: 10s
      consistency: LOCAL_QUORUM

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true