global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'scylla'
    static_configs:
      - targets: 
          - 'scylla1:10000'
          - 'scylla2:10000'
          - 'scylla3:10000'
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
